### ISSUE TITLE
Lazymux don't Work on Virtualbox Tsurugi VM

### ISSUE THREAD

**Issue by LamineSecu** [Gameye98/Lazymux#41]
HI,
Below the steps I have done to get the problem

1>= git clone https://github.com/Gameye98/Lazymux
 
2>= cd Lazymux
3>= python lazymux.py

tsurugi@lab:~/Downloads/lazymux/Lazymux$ python lazymux.py 
Traceback (most recent call last):
  File "lazymux.py", line 6, in <module>
    from core.lzmcore import *
  File "/home/tsurugi/Downloads/lazymux/Lazymux/core/lzmcore.py", line 4, in <module>
    import urllib.request
ImportError: No module named request

**Comment by LamineSecu** [comment]
It's work with python3.**
