### ISSUE TITLE
parrot os

### ISSUE THREAD

**Issue by hackverd** [Gameye98/Lazymux#99]
Traceback (most recent call last):
  File "/home/rooty/Lazymux/lazymux.py", line 6, in <module>
    from core.lzmcore import *
  File "/home/rooty/Lazymux/core/lzmcore.py", line 26, in <module>
    cache_1 = prefix+"/tmp/lazymux_1"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by Gameye98** [comment]
Use python 3 by typing

```bash
$ python lazymux.py
```
